### ISSUE TITLE
[az/arcgis] validation error for NormalizedLocation (bug)

### ISSUE THREAD

**Issue by Graham42** [CAVaccineInventory/vaccine-feed-ingest#329]
In the process of making an unrelated PR, I get a validation error from running `poetry run vaccine-feed-ingest normalize  --state ak`

```
2021-05-01T16:54:35-0400 INFO:stages/ingest.py:Normalizing ak/arcgis and saving normalized output to /tmp/tmpe9jwdngg_normalize_ak_arcgis/output
2021-05-01T16:54:36-0400 INFO:runners/ak/arcgis/normalize.py:normalizing /tmp/tmpe9jwdngg_normalize_ak_arcgis/input/d92cbd6ff2524d7e92bef109f30cb366_0.parsed.ndjson => /tmp/tmpe9jwdngg_normalize_ak_arcgis/output/d92cbd6ff2524d7e92bef109f30cb366_0.parsed.normalized.ndjson
Traceback (most recent call last):
  File "/$REPO_DIR/vaccine-feed-ingest/vaccine_feed_ingest/runners/ak/arcgis/normalize.py", line 170, in <module>
    normalized_site = _get_normalized_location(
  File "/$REPO_DIR/vaccine-feed-ingest/vaccine_feed_ingest/runners/ak/arcgis/normalize.py", line 112, in _get_normalized_location
    return schema.NormalizedLocation(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NormalizedLocation
id
  string does not match regex "^[a-z0-9_]+\:[a-z0-9_-]+$" (type=value_error.str.regex; pattern=^[a-z0-9_]+\:[a-z0-9_-]+$)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/$REPO_DIR/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/$REPO_DIR/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/$REPO_DIR/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/$REPO_DIR/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/$REPO_DIR/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/$REPO_DIR/vaccine-feed-ingest/vaccine_feed_ingest/cli.py", line 219, in normalize
    ingest.run_normalize(site_dir, output_dir, timestamp, validate, dry_run)
  File "/$REPO_DIR/vaccine-feed-ingest/vaccine_feed_ingest/stages/ingest.py", line 225, in run_normalize
    subprocess.run(
  File "/$HOME/.pyenv/versions/3.9.2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/$REPO_DIR/vaccine-feed-ingest/vaccine_feed_ingest/runners/ak/arcgis/normalize.py', PosixPath('/tmp/tmpe9jwdngg_normalize_ak_arcgis/output'), PosixPath('/tmp/tmpe9jwdngg_normalize_ak_arcgis/input')]' returned non-zero exit status 1.
```

**Comment by Graham42** [comment]
the az arcgis normalizer is formatting an id with multiple colons
https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/db0a150f4df42f71f49fc3727b74045191cbf3fd/vaccine_feed_ingest/runners/az/arcgis/normalize.py#L46

but the schema only allows an id with one colon:
https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/blob/a0dcd65ca32a8e02478770865c2314ef23ab5924/vaccine_feed_ingest_schema/location.py#L40

**Comment by Graham42** [comment]
I'll try to open a PR for this

**Comment by bryanculbertson** [comment]
@Graham42 Looks like there is a PR for `az/arcgis`: https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/326

**Comment by Graham42** [comment]
Thanks! I search the issues, but I should have searched the PRs too. I've found this issue exists for some other arcgis normalizers so I'll open a PR for those. I intend to leave the `az/arcgis` change to #326

**Comment by Graham42** [comment]
fixed by https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/326

**Comment by bryanculbertson** [comment]
@Graham42 I mixed up `az` and `ak` as well, we still need a fix for `az`
