### ISSUE TITLE
🐞 ValidationError in normalize for arcgis for PA

### ISSUE THREAD

**Issue by Graham42** [CAVaccineInventory/vaccine-feed-ingest#346]
To reproduce
```
poetry run vaccine-feed-ingest fetch pa/arcgis
poetry run vaccine-feed-ingest parse pa/arcgis
poetry run vaccine-feed-ingest normalize pa/arcgis
```

Results in a ValidationError
```
Traceback (most recent call last):
  File "/home/graham/dev/github.com/CAVaccineInventory/vaccine-feed-ingest/vaccine_feed_ingest/runners/pa/arcgis/normalize.py", line 114, in <module>
    normalized_site = _get_normalized_location(
  File "/home/graham/dev/github.com/CAVaccineInventory/vaccine-feed-ingest/vaccine_feed_ingest/runners/pa/arcgis/normalize.py", line 56, in _get_normalized_location
    return schema.NormalizedLocation(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NormalizedLocation
id
  string does not match regex "^[a-z0-9_]+\:[a-z0-9_-]+$" (type=value_error.str.regex; pattern=^[a-z0-9_]+\:[a-z0-9_-]+$)
```

**Comment by Graham42** [comment]
I'll take this one
