### ISSUE TITLE
Broken fetch/mo_arcgis (Error Code: 403)

### ISSUE THREAD

**Issue by alecfwilson** [CAVaccineInventory/vaccine-feed-ingest#620]
```2021-05-12T14:33:12-0700 INFO:stages/ingest.py:Fetching mo/arcgis and saving fetched output to /var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmpt0dlg887_fetch_mo_arcgis/output
2021-05-12T14:33:14-0700 INFO:runners/_shared/fetch.py:Scraping MO/arcgis into output_dir=/var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmpt0dlg887_fetch_mo_arcgis/output, with config from /Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/mo/arcgis/fetch.yml
Traceback (most recent call last):
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/_shared/fetch.py", line 53, in <module>
    arcgis_ingest.fetch_geojson(
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/ingestors/arcgis_ingest.py", line 25, in fetch_geojson
    item = gis.content.get(service_item_id)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 4573, in get
    raise e
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 4563, in get
    item = self._portal.get_item(itemid)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/_impl/_portalpy.py", line 1264, in get_item
    return self.con.post('content/items/' + itemid, self._postdata())
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 716, in post
    return self._handle_response(resp=resp,
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 514, in _handle_response
    self._handle_json_error(data['error'], errorcode)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 536, in _handle_json_error
    raise Exception(errormessage)
Exception: You do not have permissions to access this resource or perform this operation.
(Error Code: 403)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/cli.py", line 240, in fetch
    ingest.run_fetch(
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/stages/ingest.py", line 58, in run_fetch
    raise e
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/stages/ingest.py", line 53, in run_fetch
    subprocess.run(
  File "/Users/alecfwilson/.pyenv/versions/3.9.2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/_shared/fetch.py', '/var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmpt0dlg887_fetch_mo_arcgis/output', '/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/mo/arcgis/fetch.yml']' returned non-zero exit status 1.```

**Comment by eliblock** [comment]
@alecfwilson disabled this fetcher in the meantime.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
