### ISSUE TITLE
Broken parse: la/tableau ("Dimension-value": data_dict["Dimension-value"][i + 1], IndexError: list index out of range)

### ISSUE THREAD

**Issue by alecfwilson** [CAVaccineInventory/vaccine-feed-ingest#621]
```2021-05-12T14:23:05-0700 INFO:stages/ingest.py:Parsing la/tableau and saving parsed output to /var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmp86ihm82h_parse_la_tableau/output
Traceback (most recent call last):
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/la/tableau/parse.py", line 90, in <module>
    sites = parse_tableau(fin.read())
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/la/tableau/parse.py", line 76, in parse_tableau
    "Dimension-value": data_dict["Dimension-value"][i + 1],
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/cli.py", line 269, in parse
    ingest.run_parse(
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/stages/ingest.py", line 149, in run_parse
    raise e
  File "/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/stages/ingest.py", line 138, in run_parse
    subprocess.run(
  File "/Users/alecfwilson/.pyenv/versions/3.9.2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/alecfwilson/Sites/vaccine-feed-ingest/vaccine_feed_ingest/runners/la/tableau/parse.py', '/var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmp86ihm82h_parse_la_tableau/output', '/var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmp86ihm82h_parse_la_tableau/input', 'None']' returned non-zero exit status 1.```

**Comment by nuchi** [comment]
I can take a look at this tomorrow. (I wrote the `parse.py` for this.)
