### ISSUE TITLE
tx/harriscounty_gov arcGIS data doesnt seem to exist anymore

### ISSUE THREAD

**Issue by MoralCode** [CAVaccineInventory/vaccine-feed-ingest#718]
Related to #646 

CC @cdjj 

Trying to run the fetcher currently yields:

```
Traceback (most recent call last):
  File "/home/ace/Projects/Current/Contributions/vaccine-feed-ingest/vaccine_feed_ingest/runners/_shared/fetch.py", line 53, in <module>
    arcgis_ingest.fetch_geojson(
  File "/home/ace/Projects/Current/Contributions/vaccine-feed-ingest/vaccine_feed_ingest/ingestors/arcgis_ingest.py", line 30, in fetch_geojson
    [layer.properties.name for layer in item.layers],
AttributeError: 'NoneType' object has no attribute 'layers'
```
`item` comes from the line `    item = gis.content.get(service_item_id)`. Because it is `None`, that suggest that the serviceItemId for this fetcher is no longer valid

I suspect it and the layer name have changed to 15f20c50666a45f5be5cce3a4a655a20 and Weekly_HCPH_VDU_Site_Update  respectively,

**Comment by cdjj** [comment]
Sure looks like it --- thanks, @MoralCode !
